-- phpMyAdmin SQL Dump
-- version 4.5.1
-- http://www.phpmyadmin.net
--
-- Host: 127.0.0.1
-- Generation Time: Nov 21, 2018 at 08:05 AM
-- Server version: 10.1.19-MariaDB
-- PHP Version: 5.6.28

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `nut`
--

-- --------------------------------------------------------

--
-- Table structure for table `mpasi`
--

CREATE TABLE `mpasi` (
  `id` int(10) NOT NULL,
  `nama` varchar(60) NOT NULL,
  `bahan` varchar(400) NOT NULL,
  `resep` text NOT NULL,
  `usia` varchar(50) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

--
-- Dumping data for table `mpasi`
--

INSERT INTO `mpasi` (`id`, `nama`, `bahan`, `resep`, `usia`) VALUES
(1, 'Bubur Ubi Bayam Polong ', '30 gram Bayam\r\n25 gram Butter Tawar\r\n30 gram Daun Bawang\r\n25 gram Kacang Polong Beku\r\n200 ml Kaldu\r\n25 gram Ubi', 'Pertama buang tangkai bayam dan cuci bayam hingga bersih\r\n\r\nKemudian kupas ubi kemudian potong kecil-kecil.\r\n\r\nSelanjutnya iris halus daun bawang\r\n\r\nKemudian panaskan butter dalam wajan untuk menumis daun bawang selama 2-3 menit hingga layu.\r\n\r\nLalu masukkan ubi dan kaldu. masak selama 7 hingga 8 menit hingga mendidih dan ubi matang.\r\n\r\nTambahkan kacang polong dan bayam, masak selama 3 menit hingga lunak. Angkat, setelah dingin, haluskan. Tambahkan ASI bila terlalu kental.', '6 bulan'),
(2, 'Bubur Tahu', '1/2 sendok teh Garam Halus\r\n500 cc Kaldu\r\n10 gram Margarin\r\n50 gram Tahu\r\n20 gram Tepung Beras\r\n50 gram Tomat\r\n40 gram Wortel', 'Pertama potong dadu kecil tahu.\r\n\r\nKemudian kupas wortel kemudian serut halus\r\n\r\nSelanjutnya kupas tomat kemudian cincang halus\r\n\r\nKemudian campur tahu, tepung kacang hijau, tepung beras, wortel, dan tomat dalam mangkuk tahan panas. aduk rata.\r\n\r\nLalu tambahkan air kaldu, beri garam dan margarine, aduk rata kembali.\r\n\r\nMasukkan mangkuk ke dalam dandang, kukus hingga semua bahan matang. Angkat, tuang daam piring bayi, sajikan setelah agak dingin.', '6 bulan'),
(3, 'Bubur Pisang Jeruk', '1/2 buah Jeruk Baby\r\n1 buah Pisang Ambon', 'Pertama kupas pisang dan lumatkan menggunakan garpu.\r\n\r\nKemudian peras jeruk baby, kemudian campurkan ke dalam pisang yang telah dihaluskan aduk hingga rata. sajikan segera untuk si kecil.', '6 bulan'),
(4, 'Kukis Keju', '1 butir kuning telur\r\n50 gram Gula Kastor\r\n75 gram Keju Cheddar\r\n130 gram Mentega Tawar\r\n25 gram Tepung Jagung\r\n150 gram Tepung Terigu', 'Pertama parut keju kemudian sisihkan\r\n\r\nKemudian campur tepung terigu, tepung jagung dan gula dalam mangkuk.\r\n\r\nSelanjutnya potong-potong mentega tawar dan masukkan ke dalam campuran terigu.\r\n\r\nKemudian tambahkan keju, lalu aduk rata dengan tangan.\r\n\r\nLalu gilas adonan hingga setebal ½ cm lalu cetak bentuk bintang. gilas sisa dan cetak lagi hingga adonan habis. atur dalam loyang panggang yang sudah diolesi kuning telur.\r\n\r\nPanggang dalam oven bersuhu 130°C selama 10-12 menit hingga matang dan berwarna kekuningan. Angkat, pindahkan dalam baki kawat berongga hingga dingin.', '6 bulan'),
(5, 'Pisang Kuah', '50 ml Air\r\n1/4 sendok teh Kayumanis\r\n2 buah Pisang Ambon', 'Pertama rebus pisang bersama air dan kayumanis. aduk hingga mendidih. angkat.\r\n\r\nKemudian sisihkan pisang dari kuahnya, haluskan dengan saringan. Tuang ke dalam mangkuk, siram dengan kuahnya', '6 bulan'),
(6, 'Pure Beras Apricot', '100 cc Air Masak Hangat\r\n50 gram Aprikot\r\n100 cc Asi Perah\r\n50 gram Pepaya\r\n3 sendok takar Peres Susu Formula\r\n40 gram Promina Beras Merah', 'Pertama kukus 50 gram aprikot dan 50 gram pepaya hingga lunak. Sisihkan.\r\n\r\nKemudian seduh 40 gram promina beras merah dengan 100 cc air masak hangat, aduk rata.\r\n\r\nSelanjutnya tambahkan buah yang sudah dihaluskan dan 100 cc asi perah atau 3 sendok takar\r\n\r\nKemudian peres susu formula dilarutkan dalam 100 cc air matang.', '6 bulan'),
(7, 'Bubur Sayur Campur', '115 gram Brokoli\r\n175 gram Kentang\r\n300 cc Susu Formula Cair\r\n115 gram Wortel', 'Pertama siapkan susu formula cair, yaitu 3 sendok takar peres susu bubuk formula kemudian larutkan dalam 300 cc air matang.\r\n\r\nKemudian cuci brokoli, potong sesuai kuntum. kupas wortel dan kentang, cuci, lalu potong dadu kecil.\r\n\r\nSelanjutnya masukkan sayuran dalam panci kecil, tambahkan 250 cc air lalu masak hingga matang.\r\n\r\nKemudian haluskan dengan blender hingga lembut. tuang ke dalam mangkuk. Sajikan.', '6 bulan'),
(8, 'Havermut Saus Pepaya', '100 ml Air\r\n50 gram Havermut Instan\r\n50 gram Pepaya\r\n150 ml Susu Cair', 'Pertama kupas pepaya kemudian potong dadu kecil.\r\n\r\nKemudian seduh havermut dengan air panas, aduk rata.\r\n\r\nSelanjutnya tambahkan susu cair sedikit demi sedikit sambil diaduk rata.\r\n\r\nKemudian lumatkan pepaya dengan garpu atau saringan kawat.\r\n\r\nLalu tuang havermut dalam mangkuk kecil, siram dengan saus papaya lalu sajikan segera.', '6 bulan'),
(9, 'Kentang Dori Saus Bayam', '50 gram Bayam\r\n50 gram Ikan Dori\r\n100 ml Kaldu Ikan\r\n50 gram Keju Parut\r\n1 buah Kentang\r\n1 sendok teh Tepung Maizena', 'Pertama kukus 1 buah kentang dan 50 gram ikan dori secara terpisah lalu haluskan.\r\n\r\nKemudian masak 50 gram bayam dengan 100 ml kaldu ikan, lalu haluskan.\r\n\r\nSelanjutnya tambahkan 1 sendok teh tepung maizena yang sudah dilarutkan dengan air hingga kental.\r\n\r\nKemudian campur kentang dan dori, beri saus bayam dan taburi dengan 50 gram keju parut.', '6 bulan'),
(10, 'Sup Apel', '1 buah Apel\r\n250 ml Kaldu Ayam\r\n30 gram Kentang\r\n30 gram Wortel', 'Pertama kupas apel, wortel, dan kentang. Cuci bersih dan potong dadu.\r\n\r\nKemudian didihkan kaldu, masukkan apel, wortel, dan kentang. rebus hingga bahan matang. Angkat.\r\n\r\nSelanjutnya setelah agak dingin, haluskan buah dan sayuran rebus dalam blender. Tuang ke mangkuk, sajikan.', '6 bulan'),
(11, 'Bubur Roti Susu Pisang', '200 cc Air Matang Hangat\r\n1 buah Pisang Ambon\r\n2 lembar Roti Tawar\r\n4 sendok takar Susu Formula', 'Pertama buang pinggiran roti tawar dan sobek sobek kecil.\r\n\r\nKemudian campur air hangat dengan susu formula, aduk merata.\r\n\r\nSelanjutnya masukkan roti tawar ke dalam susu hangat, lumatkan hingga halus dan merata.\r\n\r\nKemudian lumatkan pisang hingga halus dengan menggunakan garpu, lalu campur ke dalam roti tawar yang sudah halus dan aduk rata. Segera sajikan selagi hangat.', '6 bulan'),
(12, 'Bubur Stroberi Susu', '50 cc ASI\r\n50 gram Stroberi', 'Pertama bersihkan stoberi dengan membuang daunnya, cuci, kemudian potong kecil.\r\n\r\nKemudian asi dapat digantikan dengan 2 sendok takar susu formula bubuk\r\n\r\nSelanjutnya masukkan potongan stroberi dan susu dalam food processor atau bisa juga menggunakan blender hingga halus.\r\n\r\nKemudian tuang ke dalam mangkuk kecil, sajikan segera untuk buah hati anda.', '6 bulan'),
(13, ' Jus Jagung Susu', '150 cc ASI\r\n100 cc Air Matang\r\n1 sendok teh Gula Pasir Halus\r\n70 gram Jagung Manis', 'Pertama sisir jagung dengan menggunakan pisau.\r\n\r\nKemudian haluskan butiran jagung bersama gula dan air dengan blender.\r\n\r\nSelanjutnya setelah halus, rebus hingga mendidih sambil diaduk.\r\n\r\nKemudian angkat lalu tambahkan susu atau susu formula yang telah dicairkan dan aduk rata. Biarkan hingga dingin, kemudian sajikan.', '6 bulan'),
(14, 'Bubur Wortel', '\r\n100 cc ASI\r\n200 cc Air\r\n50 gram Wortel', 'Pertama kupas wortel kemudian potong kecil-kecil.\r\n\r\nKemudian rebus wortel dalam panci kecil hingga lunak. Angkat.\r\n\r\nSelanjutnya setelah agak dingin, haluskan dengan blender. Tuang ke dalam mangkuk.\r\n\r\nKemudian tambahkan asi atau susu formula cair, aduk rata. bila terlalu kental, tambahkan air sisa rebusan wortel. Sajikan.', '6 bulan'),
(15, 'Bubur Tepung Beras Merah dengan Alpukat', '50 gram Alpukat Matang\r\n100 ml Susu Formula\r\n20 gram Tepung Beras Merah', 'Pertama didihkan 150 ml air, sementara itu campur tepung beras merah dengan 50 ml air.\r\n\r\nKemudian kemudian masukkan cairan tepung beras ke dalam air mendidih, aduk-aduk, sampai mendidih dan kental. angkat.\r\n\r\nSelanjutnya setelah hangat, tuangi dengan asi/susu formula sampai kekentalan yang diinginkan, dinginkan.\r\n\r\nKemudian tuang dengan alpukat yang sudah dihaluskan, dan segera dihidangkan.', '6 bulan'),
(16, 'Bubur Salmon Kentang', '50 gram Ikan Salmon\r\n200 ml Kaldu Ikan\r\n50 gram Kentang', 'Pertama cuci bersih ikan salmon, pisahkan duri ikan dan potong dadu daging ikan salmon.\r\n\r\nKemudian kupas kentang, cuci bersih dan potong dadu kecil\r\n\r\nSelanjutnya rebus kaldu dalam panci kecil hingga mendidih.\r\n\r\nKemudian masukkan kentang dan salmon, masak selama 7 menit hingga bahan matang. Angkat.\r\n\r\nLalu tuang ke dalam mangkuk, haluskan dengan bantuan garpu. Sajikan setelah dingin.', '6 bulan'),
(17, 'Puree Labu Kuning', '300 cc Air\r\n100 gram Fillet Kakap, Potong Kecil-kecil\r\n1/8 sendok teh Garam\r\n75 gram Kacang Polong\r\n100 gram Labu Kuning, Potong Dadu\r\n75 gram Wortel', 'Pertama potong dadu labu kuning.\r\n\r\nKemudian kita potong kecil-kecil fillet kakap yang sudah disiapkan.\r\n\r\nSelanjutnya jerang air dalam panci kecil, masukkan potongan labu kuning, masak hingga matang.\r\n\r\nKemudian masukkan fillet kakap, masak hingga matang. kemudian, masukkan wortel dan kacang polong, masak hingga semua bahan lunak. Angkat.\r\n\r\nLalu setelah agak dingin, blender halus.\r\n\r\nSajikan dalam mangkuk kecil', '6 bulan'),
(18, 'Jus Pisang Jeruk', '200 cc Air Jeruk Manis\r\n1 buah Pisang Ambon', 'Pertama kupas pisang, potong-potong lalu lumatkan.\r\n\r\nKemudian campur pisang dengan air jeruk, aduk rata, sajikan.', '6 bulan'),
(19, 'Labu Bayam Merah Kukus', '200 ml Air Panas\r\n30 gram Bayam Merah\r\n50 gram Ikan Kakap\r\n150 gram Labu Kuning\r\n1 sendok makan Margarin', 'Pertama kupas labu kuning, cuci bersih kemudian potong dadu kecil.\r\n\r\nKemudian buang tangkai bayam merah, cuci bersih, kemudian iris halus.\r\n\r\nSelanjutnya cuci ikan kakap kemudian potong dadu kecil.\r\n\r\nKemudian campur labu, bayam cincang, ikan dan margarin dalam mangkuk kecil tahan panas.\r\n\r\nLalu tuangkan air hingga sampai semua bahan terendam, lalu aduk rata.\r\n\r\nMasukkan mangkuk ke dalam dandang, tutup dandang dan kukus hingga matang. Angkat, haluskan sebelum disajikan.', '6 bulan'),
(20, 'Bubur Sari Melon', '200 ml Air\r\n30 gram Melon\r\n20 gram Susu Bubuk Formula\r\n20 gram Tepung Beras', 'Pertama kupas melon, potong-potong kemudian blender.\r\n\r\nKemudian campur tepung beras dengan 50 ml air, aduk rata.\r\n\r\nSelanjutnya rebus 150 ml air. setelah mendidih masukkan tepung beras yang telah dicairkan. Masak sambil diaduk sampai mendidih dan matang, angkat.\r\n\r\nKemudian masukkan susu formula berbasis kedelai sambil diaduk rata. Tuang dalam piring bayi.\r\n\r\nLalu hidangkan dengan sari melon.', '6 bulan'),
(21, 'Bubur Kentang Tuna', '60 ml ASI\r\n40 gram Daging Tuna\r\n1/2 sendok makan Daun Seledri\r\n100 ml Kaldu Ayam\r\n60 gram Kentang', '\r\nPertama kupas kentang, cuci bersih, dan potong dadu.\r\n\r\nKemudian cincang halus daging ikan tuna.\r\n\r\nSelanjutnya didihkan kaldu, masukkan potongan kentang, daging tuna cincang dan daun seledri. rebus hingga kentang empuk dan smua bahan matang. Angkat\r\n\r\nKemudian tuang bubur dan susu formula lamjutan kedalam tabung blender/ mesin penghalus bumbu, haluskan hingga lembut , tuang bubur kedalam mangkuk saji, hidangkan.', '6 bulan'),
(22, 'Bananakado', 'Air Matang secukupnya\r\n100 gram Daging Buah Avokad\r\n1 buah Pisang Ambon\r\n100 cc Susu Formula', 'Pertama pisang kita kupas dan potong kecil kecil.\r\n\r\nKemudian haluskan avokad bersama pisang dan susu.\r\n\r\nSelanjutnya tuang ke dalam mangkuk kecil, sajikan.\r\n\r\nKemudian bila terlalu pekat, atur kekentalannya dengan menambahkan susu formula cair.', '6 bulan'),
(23, 'Bubur Naga Pisang', '100 ml ASI \r\n200 ml Air\r\n50 gram Buah Naga\r\n1 buah Pisang Ambon', 'Pertama kupas buah naga, cuci bersih kemudian potong kecil.\r\n\r\nKemudian kupas pisang kemudian potong kecil.\r\n\r\nSelanjutnya rebus buah naga bersama pisang hingga lunak. Angkat dan haluskan.\r\n\r\nKemudian pindahkan ke mangkuk kecil, tambahkan susu atau susu formula yang dicairkan. Aduk hingga rata.\r\n\r\nLalu sajikan saat bubur sudah dingin.', '6 bulan'),
(24, 'Bubur Saring Ikan Gabus', '500 cc Air\r\n1 siung Bawang Putih\r\n100 gram Bayam\r\n100 gram Beras\r\n100 gram Daging Ikan Gabus Segar\r\n1/2 sendok teh Garam\r\n2 buah Wortel', 'Pertama cuci beras hingga bersih. cincang halus daging ikan gabus. iris halus bayam yang sudah disiapkan. parut kasar wortel dan parut halus bawang putih.\r\n\r\nKemudian masak beras bersama air hingga menjadi bubur\r\n\r\nSelanjutnya masukkan wortel, bayam dan parutan bawang putih, masak hingga sayuran matang.\r\n\r\nKemudian masukkan ikan, bubuhkan garam. aduk dan masak terus hingga semua bahan matang. Angkat.\r\n\r\nLalu setelah agak dingin, saring memakai saringan kawat. Sajikan dalam mangkuk kecil.', '6 bulan'),
(25, 'Jus Mangga Melon', '100 ml ASI\r\n50 ml Air Jeruk Manis\r\n100 ml Air Matang\r\n50 gram Mangga\r\n50 gram Melon', 'Pertama kupas mangga, melon kemudian cuci bersih dan potong dadu kecil.\r\n\r\nKemudian haluskan 50 gram mangga dan 50 gram melon menggunakan blender.\r\n\r\nSelanjutnya tambahkan 50 ml air jeruk manis dan 100 ml asi atau 3 sendok takar susu formula yang sudah diseduh dalam 100 ml air matang.', '6 bulan'),
(26, 'Bubur Pisang Susu', '150 cc Air\r\n100 gram Pisang Ambon\r\n150 cc Susu Formula\r\n', 'Pertama blender pisang dengan tambahan sedikit air. Saring menggunakan saringan kawat.\r\n\r\nKemudian rebus air di panci kecil, masukkan pisang aduk hingga mendidih dan kental. Angkat.\r\n\r\nSelanjutnya tambahkan asi atau susu formula yang telah dicairkan, aduk rata. sajikan.', '6 bulan'),
(27, 'Jus Pisang Kurma', '100 ml ASI\r\n100 ml Air Matang\r\n2 sendok makan Jeruk Manis\r\n4 buah Kurma\r\n1 buah Pisang Ambon', 'Pertama potong 1 buah pisang ambon dan 4 buah kurma.\r\n\r\nKemudian haluskan menggunakan blender.\r\n\r\nSelanjutnya tambahkan 2 sendok makan jeruk manis dan 100 ml asi atau 3 sendok takar susu formula yang sudah diseduh dengan 100 ml air matang bila tekstur kurang encer.', '6 bulan'),
(28, 'Pure Ayam Brokoli', '50 gram Ayam\r\n50 gram Brokoli\r\n100 ml Kaldu Ayam\r\n50 gram Labu Kuning', 'Pertama rebus 50 gram labu kuning dengan 100 ml kaldu ayam hingga matang.\r\n\r\nKemudian kukus 50 gram ayam dan 50 gram brokoli secara terpisah.\r\n\r\nSelanjutnya masukkan semua bahan ke dalam blender. Proses hingga halus.', '6 bulan'),
(29, 'Pure Ubi Ungu', '100 cc ASI\r\ncc Air Matang\r\n25 gram Bayam Merah\r\n150 cc Kaldu Ayam\r\n25 gram Ubi Ungu', 'Pertama kupas ubi ungu, cuci bersih, kemudian potong dadu.\r\n\r\nKemudian kukus ubi ungu hingga lunak. angkat, sisihkan.\r\n\r\nSelanjutnya buang tangkai bayam, cuci bersih, dan cincang halus.\r\n\r\nKemudian rebus bayam merah dengan kaldu selama 3 menit hingga matang.\r\n\r\nLalu campur ubi dan bayam merah, haluskan dengan blender.\r\n\r\nTuang ke dalam mangkuk, tambahkan ASI atau susu formula yang telah dicairkan. Sajikan segera.', '6 bulan'),
(30, 'Pure Pepaya Jeruk', '150 ml Air Jeruk Manis\r\n100 gram Pepaya', 'Pertama kupas kulit pepaya kemudian potong dadu.\r\n\r\nKemudian masukkan keblender dan tambahkan air jeruk, haluskan.\r\n\r\nSelanjutnya tuang ke dalam mangkuk kecil, sajikan untuk si kecil.', '6 bulan'),
(31, 'Sari Avokad Susu', '100 gram Avokad\r\n1 sendok teh Gula Pasir\r\n200 cc Susu Formula Cair', 'Pertama haluskan avokad bersama susu dan gula pasir.\r\n\r\nKemudian tuang ke dalam mangkuk dan atur kekentalannya.', '6 bulan'),
(32, 'Sup Kacang Polong', '100 gram Kacang Polong\r\n100 ml Kaldu Ayam\r\n100 gram Wortel', 'Pertama rebus 100 gram kacang polong dan 100 gram wortel yang sudah dipotong-potong. Haluskan keduanya dengan blender.\r\n\r\nKemudian masak kembali kacang polong wortel dengan menambahkan 100 ml kaldu ayam', '6 bulan'),
(33, 'Kaserol Daging Wortel', '1 batang daun seledri\r\n25 gram Bawang Bombay\r\n50 gram Daging Giling\r\n20 ml Jus Apel\r\n40 ml Kaldu Sapi\r\n15 gram Keju Chedar\r\n1/2 sendok teh Mentega Tawar\r\n1 sendok teh Tepung Terigu\r\n30 gram Tomat\r\n50 buah Wortel', 'Pertama kupas wortel, cuci bersih, dan potong kecil-kecil.\r\n\r\nKemudian kupas bawang bombay dan iris halus.\r\n\r\nSelanjutnya haluskan tomat.\r\n\r\nKemudian parut keju.\r\n\r\nLalu panaskan mentega, tumis bawang bombay hingga harum.\r\n\r\nTambahkan daging giling, wortel dan tomat hingga layu dan matang.\r\n\r\nTambahkan jus apel, kaldu dan daun seledri. Taburi tepung terigu. Masak hingga air berkurang.\r\n\r\nSajikan dalam mangkuk, taburi keju.', '10 bulan'),
(34, 'Kembang Kol Kentang Panggang', '1 siung Bawang Putih\r\n50 gram Daging Ayam\r\n25 gram Keju Parut\r\n100 gram Kembang Kol\r\n100 gram Kentang\r\n1/2 sendok teh Mentega Tawar', 'Pertama kukus 100 gram kentang dan 100 gram kembang kol. haluskan keduanya.\r\n\r\nKemudian tumis 1 siung bawang putih, menggunakan 1/2 sendok teh mentega tawar.\r\n\r\nSelanjutnya masukkan ayam, masak hingga matang.\r\n\r\nKemudian campurkan dengan kentang, taburi 25 gram keju parut. panggang hingga matang.', '10 bulan'),
(35, ' Pure Kentang', '100 cc ASI\r\n100 cc Air Matang\r\n100 gram Kentang', 'Pertama rebus 100 gram kentang, haluskan dengan menekan-nekan hingga halus.\r\n\r\nKemudian tambahkan 100 cc asi perah atau 3 sendok takar peres susu formula yang dilarutkan dalam 100 cc air matang.\r\n\r\nSelanjutnya aduk hingga rata', '10 bulan'),
(36, 'Bubur Beras Merah dan Pepaya', '1 sendok makan Air Jeruk Manis\r\n200 cc Air Matang Hangat\r\n50 gram Pepaya\r\n200 cc Susu Formula\r\n50 gram Tepung Beras Merah ', 'Pertama campur tepung dengan air hangat, aduk\r\n\r\nKemudian tambahkan susu hangat, aduk rata kembali. sajikan dengan pepaya.\r\n\r\nSelanjutnya haluskan pepaya dengan garpu, saringan kawat atau blender.\r\n\r\nKemudian campur dengan air jeruk, aduk rata.', '10 bulan'),
(37, 'Nasi Merah', '5 cm kayumanis\r\n100 cc Air\r\n75 gram Bawang Bombay\r\n1 siung Bawang Putih\r\n100 gram Beras\r\n2 butir Cengkih\r\n150 gram Daging Ikan Kakap\r\n1/2 sendok teh Garam\r\n1/4 sendok teh Gula Pasir\r\n4 sendok makan Minyak Goreng\r\n250 gram Paprika Merah\r\n1 butir Pekak\r\n100 gram Tomat Merah', 'Pertama cuci bersih paprika merah dan tomat, kemudian parut.\r\n\r\nKemudian cuci bersih daging kakap, kemudian cincang halus.\r\n\r\nSelanjutnya cincang halus bawang bombay dan bawang putih.\r\n\r\nKemudian haluskan parutan paprika dan tomat bersama air dengan blender.\r\n\r\nLalu panaskan 1 sendok makan minyak goreng dalam wajan di atas api sedang. masukkan ikan kakap, tumis sambil diaduk-aduk hingga matang. angkat.\r\n\r\nTuang 3 sendok makan minyak goreng dalam wajan, tumis bawang bombay dan bawang putih hingga lunak dan harum. Masukkan kayumanis, pekak, dan cengkih.\r\n\r\nMasukkan beras ke dalam rice cooker. Tambahkan tumisan bawang dan pasta paprika-tomat. Tambahkan gula pasir dan garam. Aduk rata, tutup rice cooker dan tekan tombol masak. .\r\n\r\nSetelah tombol kembali ke posisi semula, lanjutkan menanak selama 3-5 menit agar nasi kesat. Masukkan tumis ikan, aduk rata. Buang kayumanis, pekak dan cengkih. Sajikan hangat.', '10 bulan'),
(38, 'Makaroni Sayur Panggang', '50 gram Bayam\r\n100 gram Daging Sapi\r\n100 gram Makaroni\r\n1 butir telur\r\n2 sendok makan Margarin\r\n75 cc Susu Cair\r\n50 gram Wortel', 'Pertama rebus makaroni hingga matang.\r\n\r\nKemudian kupas wortel, cuci bersih, kemudian parut halus.\r\n\r\nSelanjutnya buang tangkai bayam, cuci bersih daun bayam, dan cincang halus.\r\n\r\nKemudian cincang halus daging sapi.\r\n\r\nLalu kocok sebutir telur. sisihkan\r\n\r\nPanaskan oven 180°C, olesi loyang persegi kecil dengan margarin.\r\n\r\nCampur dalam mangkuk, makaroni, wortel, bayam, daging cincang, margarin dan keju. Aduk rata.\r\n\r\nMasukkan telur kocok, dan tuangi susu sedikit demi sedikit sambil diaduk rata.\r\n\r\nTuang adonan ke dalam loyang, taburi keju lalu panggang 75 menit hingga matang lalu angkat.\r\n\r\nSetelah dingin, potong-potong lalu sajikan.', '10 bulan'),
(39, 'Pure Kentang Wortel', '100 ml ASI\r\n30 gram Jagung Manis\r\n200 ml Kaldu\r\n50 gram Kentang\r\n50 gram Wortel', 'Pertama kupas kentang dan wortel, cuci bersih, dan potong dadu.\r\n\r\nKemudian pipil jagung mansi menggunakan pisau.\r\n\r\nSelanjutnya rebus kentang, wortel, dan jagung manis dengan kaldu hingga matang. Angkat.\r\n\r\nKemudian haluskan lalu tuang ke dalam mangkuk. Tambahkan asi atau susu formula yang telah dicairkan. Aduk rata dan sajikan.', '10 bulan'),
(40, 'Sereal Kiwi ', '100 ml Air Matang\r\n150 ml Air Panas\r\n100 ml Asi\r\n1 buah Kiwi\r\n30 gram Sereal Instan', 'Pertama campur sereal instan dengan air panas sambil diaduk hingga kental.sisihkan.\r\n\r\nKemudian kupas kiwi, cuci bersih, kemudian potong dadu.\r\n\r\nSelanjutnya haluskan kiwi bersama susu dalam blender. tuang ke dalam sereal, aduk rata. Sajikan hangat dalam mangkuk kecil.', '10 bulan'),
(41, 'Nasi Jamur', '500 cc Air\r\n50 gram Beras\r\n50 gram Daging Sapi\r\n50 gram Jamur\r\n1 sendok makan Minyak Sayur', 'Pertama cuci bersih jamur, kemudian cincang halus.\r\n\r\nKemudian cincang halus daging sapi.\r\n\r\nSelanjutnya cuci bersih beras.\r\n\r\nKemudian rebus beras bersama daging giling sambil diaduk hingga matang dan kental\r\n\r\nLalu masukkan jamur cincang dan minyak sayur. Aduk rata dan angkat. \r\nTuang 1 porsi di piring hias menarik.', '10 bulan'),
(42, 'Kentang Kukus Daging Cincang', '30 ml Air\r\n30 gram Buncis\r\n50 gram Daging Cincang\r\n50 gram Kentang\r\n1 sendok makan Margarin', 'Pertama kupas kentang, cuci bersih, kemudian potong dadu kecil.\r\n\r\nKemudian cuci buncis, buang serat buncis kemudian iris halus\r\n\r\nSelanjutnya masukkan kentang, daging dan buncis dalam mangkuk tahan panas.tambahkan margarin dan air, aduk rata.\r\n\r\nKemudian panaskan dandang berisi air, kukus campuran kentang hingga matang. angkat, sajikan setelah dingin.', '10 bulan'),
(43, 'Melon Kuning Susu', '200 cc Air\r\n1 sendok makan Maizena\r\n70 gram Melon Kuning\r\n3 sendok makan Susu Formula Bubuk', 'Pertama kupas melon, cuci bersih, dan potong dadu.\r\n\r\nKemudian larutkan maizena dengan 2 sendok makan air.\r\n\r\nSelanjutnya saus susu: rebus air dan maizena hingga kental sambil diaduk. angkat dari api.\r\n\r\nKemudian tambahkan susu bubuk, aduk hingga tercampur rata lalu sisihkan.\r\n\r\nLalu haluskan melon, tuang ke dalam gelas kecil, campur dengan saus susu.', '10 bulan'),
(44, 'Jus Melon Susu', '200 gram Melon Kuning\r\n100 cc Susu Formula Cair', 'Pertama kupas melon, cuci dengan air matang lalu potong kecil.\r\n\r\nKemudian masukkan melon dan susu ke dalam blender lalu haluskan. tuang ke dalam gelas, sajikan.', '10 bulan'),
(45, 'Hunkue Pisang Madu', '2 sendok makan Madu\r\n50 gram Maizena\r\n1 buah Pisang Ambon\r\n250 cc Susu Cair\r\n50 gram Tepung Hunkue', 'Pertama larutkan tepung hunkue dengan air secukupnya.\r\n\r\nKemudian iris pisng ambon setebal 1 cm.\r\n\r\nSelanjutnya didihkan susu, masukkan larutan hunkue sambil diaduk hingga matang dan licin (tidak mengeluarkan gelembung), angkat.\r\n\r\nKemudian tuang adonan hunkue ke dalam mangkuk, taruh potongan pisang di atasnya dan biarkan mengeras. sajikan dengan saus madu.\r\n\r\nLalu membuat saus madu:\r\n\r\nDidihkan susu, masukkan maizena sambil diaduk. Tambahkan madu, aduk rata.', '10 bulan'),
(46, 'Tim Saring Nasi Tempe', '\r\n2 sendok makan Beras Putih\r\n1 sendok makan Daging Ayam Giling\r\n750 ml Kaldu Sapi\r\n50 gram Tempe\r\n25 gram Wortel', 'Pertama potong dadu tempe.\r\n\r\nKemudian kupas wortel, cuci bersih, dan potong korek api.\r\n\r\nSelanjutnya rebus kaldu sapi, beras, daging ayam giling, dan tempe sambil diaduk-aduk hingga menjadi bubur.\r\n\r\nKemudian masukkan wortel, tunggu mendidih lagi, angkat dan dinginkan.\r\n\r\nLalu haluskan memakai saringan kawat kemudian sajikan.', '10 bulan'),
(47, 'Sup Bubur Jagung', '3 gelas Air Kaldu Ayam\r\n2 sendok makan Brokoli\r\n2 sendok makan Daging Ayam\r\n1 buah Jagung Manis Parut\r\n1 mangkok Kecil Nasi\r\n2 sendok makan Keju Parut', 'Pertama parut jagung manis.\r\n\r\nKemudian cincang halus daging ayam.\r\n\r\nSelanjutnya potong brokoli per kuntum.\r\n\r\nKemudian rebus air kaldu,jagung parut,daging ayam,nasi,\r\n\r\nLalu setelah air menyusut setengah.\r\nMasukan brokoli dan keju,masak sampai menjadi bubur.', '10 bulan'),
(48, 'Tim Hati Ayam Beras Merah', '500 ml Air Kaldu\r\n20 sendok makan Beras Merah\r\n20 gram Brokoli\r\n20 gram Hati Ayam\r\n20 gram Keju Parut\r\n20 gram Wortel', 'Pertama cincang brokoli.\r\n\r\nKemudian kupas wortel, cuci bersih, dan haluskan.\r\n\r\nSelanjutnya rebus beras merah bersama hati ayam dengan air kaldu hingga lunak dan mengental\r\n\r\nKemudian kemudian masukkan brokoli ,wortel yang sudah dihaluskan .aduk hingga matang,angkat dan biarkan dingin\r\n\r\nLalu sebelum disajikan taburi dengan keju parut.Sajikan', '10 bulan'),
(49, 'Kue Biskuit Pir', '\r\n350 gram Buah Pir\r\n3 butir Kuning Telur\r\n300 gram Mentega\r\n250 gram Susu Formula\r\n1 butir Telur\r\n600 gram Tepung Terigu\r\n1/2 sendok teh Vanili', '\r\nPertama panaskan mentega kemudian sisihkan.\r\n\r\nKemudian kocok telur dengan mixer.\r\n\r\nSelanjutnya kupas buah pir dan potong dadu.\r\n\r\nKemudian haluskan pir dengan blender\r\n\r\nLalu campurkan pur halus, telur yang sudah dikocok, tepung terigu, mentega, mentega, susu dan vanili\r\n\r\nAduk hingga menjadi adonan yang dapat dibentuk\r\n\r\nTata adonan di loyang dan olesi dengan kuning telur\r\n\r\nPanggang dalam oven dengan suhu 180-200 celcius selama 15 menit Setelah dingin, siap disajikan', '10 bulan'),
(50, 'Biskuit Wortel Havermut', '1 sendok teh Bumbu Spekuk\r\n200 gram Gula Pasir Halus\r\n130 gram Margarine\r\n1/2 sendok teh Soda Kue\r\n1 sendok teh Susu Bubuk\r\n2 butir Telur\r\n30 gram Terigu\r\n200 gram Wortel', 'Pertama kupas wortel, cuci bersih, dan parut halus.\r\n\r\nKemudian kocok margarin atau mentega bersama gula sebentar saja sampai gula larut.\r\n\r\nSelanjutnya masukan telur lalu kocok sebentar.\r\n\r\nKemudian masukkan berturut-turut wortel,havermut, dan tepung terigu yang sudah diayak bersama soda kue, bumbu spekuk,dan susu bubuk. aduk dengan sendok.\r\n\r\nLalu sendokan adonan diatas loyang besemir margarine.Beri jarak antara adonan satu dengan yang lainnya.\r\n\r\nPanggang dalam oven panas sedang selama 15 menit atau sampai matang. Angkat, sajikan.', '10 bulan'),
(51, 'Bubur Beras Kacang Hijau Saring', '\r\n20 gram Beras\r\n10 gram Daun Bayam\r\n25 gram Hati Ayam\r\n10 gram Kacang Hijau\r\n20 gr Tomat\r\n20 gr Wortel', 'Pertama rendam beras dan kacang hijau semalaman. kemudian cuci beras dan kacang hijau hingga bersih.\r\n\r\nKemudian beras dan kacang hijau tersebut ditim dalam 150 cc atau 3/4 gelas air.\r\n\r\nSelanjutnya apabila sudah setengah matang, masukkan hati dan wortel. Tunggu hingga hati sedikit lunak.\r\n\r\nKemudian masukkan bayam, tomat dan sedikit garam.\r\n\r\nLalu tunggu sampai masak, kemudian diangkat.\r\n\r\nTim tersebut kemudian disaring dengan saringan.', '10 bulan'),
(52, 'Bola-Bola Tempe', '60 bayam\r\n2 siung Bawang Putih\r\n2 butir Telur\r\n1 butir Telur\r\n250 gram Tempe\r\n50 gram Tepug Terigu\r\n50 gram Tepung Panir\r\n1 sendok makan Tepung Terigu', 'Pertama haluskan tempe.\r\n\r\nKemudian kocok lepas telur\r\n\r\nSelanjutnya cuci bersih daun bayam dan iris halus.\r\n\r\nKemudian kocok lepas telur\r\n\r\nLalu haluskan bawang putih.\r\n\r\nCampur tempe, telur, tepung terigu , irisan daun bayam, dan bawang putih cincang. Aduk rata.\r\n\r\nAmbil setengah sendok makan adonan tempe. bentuk menjadi bulatan. Gulingkan diatas tepung terigu. \r\nLalu celupkan kedalam kocokan telur dan taburi dengan tepung panir.\r\n\r\nPanaskan minyak. goreng adonan hingga matang dan berwarna kuning kecoklatan. Angkat , sajikan.', '10 bulan'),
(53, 'Bubur Saring Kentang dengan Ayam dan Buncis', '250 ml Air\r\n25 gram Buncis Potong Kecil\r\n30 gram Daging Ayam\r\n100 gram Kentang\r\n25 gram Tahu Potong Kecil\r\n25 gram Wortel Iris Halus', '\r\nPertama kupas kentang. Cuci bersih, dan potong dadu.\r\n\r\nKemudian cincang daging ayam.\r\n\r\nSelanjutnya potong tahu kecil-kecil.\r\n\r\nKemudian buang serat buncis, cuci bersih, dan iris halus.\r\n\r\nLalu kupas woretl, cuci bersih, dan iris halus\r\n\r\nRebus kentang dan ayam hingga empuk\r\n\r\nTambahkan buncis, wortel dan tahu aduk hingga matang\r\n\r\nAngkat dinginkan sebentar kemudian saring', '10 bulan'),
(54, 'Bubur Saring Teri Kentang', '600 ml Air\r\n20 gram Beras\r\n50 gram Kentang Potong Dadu\r\n1 batang Seledri Iris Halus\r\n50 gram Teri Nasi Basah Cuci Lalu Tririskan\r\n25 gram Wortel Parut', 'Pertama cuci beras hingga bersih.\r\n\r\nKemudian cuci ikan teri kemudian tiriskan.\r\n\r\nSelanjutnya kupas kentang, cuci bersih, dan potong dadu.\r\n\r\nKemudian kupas wortel, cuci bersih, dan parut halus.\r\n\r\nLalu iris seledri halus\r\n\r\nRebus beras hingga matang\r\n\r\nTambahkan teri, kentang, wortel dan seledri\r\n\r\nAduk terus hingga semua matang lalu angkat\r\n\r\nDinginkan sebentar kemudian saring', '10 bulan'),
(55, 'Bubur Jagung Manis Oatmeal', '100 ml Air\r\n1 lembar Daun Pandan\r\n1 buah Jagung Manis\r\n2 sendok makan Oatmeal', 'Pertama serut jagung, blender dgn 100 ml air, saring. Buang ampasnya.\r\n\r\nKemudian masak sari jagung bersama oatmeal dan daun pandan dgn api kecil sampe matang (kalis).\r\n\r\nSelanjutnya jika suka manis, boleh tambah dgn sedikit gula aren.\r\n\r\nKemudian hidangkan selagi hangat.', '10 bulan'),
(56, 'Bubur Susu Maizena Pepaya Sirsak', '200 ml Air\r\n5 gram Gula Pasir\r\n50 gram Pepaya\r\n10 gram Sari Sirsak\r\n3 sendok makan Susu Formula Bubuk\r\n20 gram Tepung Maizena', 'Pertama kupas pepaya, cuci bersih, kemudian haluskan.\r\n\r\nKemudian cairkan tepung maizena dengan 50 ml air, sisihkan.\r\n\r\nSelanjutnya rebus 150 ml air sampai mendidih. masukkan tepung maizena yang sudah di cairkan , masak hingga mendidih, angkat dari api.\r\n\r\nKemudian tuang ke dalam bubur, susu formula bubuk sambil di aduk rata.\r\n\r\nLalu siapkan dengan di tambah dengan sari pepaya dan sirsak yang telah di campur dan di beri gula.\r\n\r\nSiap di suapkan pada bayi dengan sendok kecil.', '10 bulan'),
(57, 'Pure Pisang Saus Mangga', '150 ml ASI\r\n3 sendok makan Air Jeruk Manis\r\n50 gram Mangga\r\n1 buah Pisang Ambon Kecil', 'Pertama pisang ambon kecil dikupas dan potong kecil.\r\n\r\nKemudian begitu juga dengan mangga dipotong kecil.\r\n\r\nSelanjutnya dengan menggunakan food processor kita haluskan pisang bersama air jeruk manis.\r\n\r\nKemudian tuang ke dalam mangkuk, dan sisihkan.\r\n\r\nLalu lumatkan mangga bersama susu cair, siram ke atas pure pisang.\r\n\r\nSajikan hangat.', '10 bulan'),
(58, 'Nasi Tim Beras Merah Campur Sayuran', '\r\n25 gram Beras Merah\r\n15 gram Brokoli\r\n15 gram Daging Sapi\r\n15 gram Kembang Kol\r\n1 butir Kuning Telur\r\n50 cc Santan Encer\r\n1 sendok makan Tepung Beras', 'Pertama rendam beras merah selama 2 jam kemudian cuci bersih.\r\n\r\nKemudian cincang halus daging sapi.\r\n\r\nSelanjutnya cincang halus brokoli dan kembang kol.\r\n\r\nKemudian kocok kuning telur.\r\n\r\nLalu didihkan air dan masukkan beras, masak hingga menjadi bubur.\r\n\r\nCampur tepung beras ,brokoli, kembang kol, daging sapi, aduk rata.\r\n\r\nTuang dalam wadah tahan panas dan masukkan santan sampai bahan terendam.\r\n\r\nTaruh wadah tahan panas tersebut dalam panci berisi air, tim hingga matang.\r\n\r\nSesaat sebelum diangkat, tambahkan kocokan kuning telur.\r\n\r\nSiap dihidangkan.', '10 bulan'),
(59, 'Tim Jagung Ayam Tempe', '25 gram Bayam\r\n50 gram Daging Ayam Giling\r\n50 gram Jagung Muda\r\n625 ml Kaldu Ayam\r\n1 sendok teh Mentega\r\n50 gram Tempe', 'Pertama serut jagung muda dan haluskan.\r\n\r\nKemudian cincang halus daging ayam.\r\n\r\nSelanjutnya kukus tempe dan haluskan.\r\n\r\nKemudian cuci bersih bayam dan iris halus.\r\n\r\nLalu campur jagung dengan air lalu aduk dan kemudian disaring .\r\n\r\nCampur air jagung, kaldu, daging ayam, dan tempe lalu masak hingga menjadi bubur lalu angkat.\r\n\r\nMasukkan bahan lainnya dan aduk rata.\r\n\r\nTuang kedalam pinggan tahan panas lalu kukus sampai matang.\r\n\r\nSajikan selagi hangat.', '10 bulan'),
(60, 'Tim Saring Bayam Merah', '1 Kuning telur\r\n25 gram Bayam Merah\r\n2 sendok makan Beras Merah\r\n25 gram Daging Sapi\r\n450 ml Kaldu Sapi\r\n200 ml Santan\r\n25 gram Tomat', 'Pertama cincang halus daging sapi.\r\n\r\nKemudian cuci bersih bayam merah dan iris kasar.\r\n\r\nSelanjutnya cincang halus tomat dan buang bijinya.\r\n\r\nKemudian rebus beras merah dan daging sapi giling dalam kaldu sapi hingga menjadi bubur.\r\n\r\nLalu masukkan sisa bahan, masak hingga matang. angkat dan didihkan\r\n\r\nHaluskan dalam blender atau disaring dengan cara menekan-nekan makanan tim tersebut pada saringan kawat\r\n\r\nSajikan dalam mangkuk yang menarik.', '10 bulan'),
(61, 'Tim Hati Ayam', '50 gram Bayam\r\n20 gram Beras Merah\r\n25 gram Hati Ayam\r\n150 ml Kaldu\r\n1 sendok teh Margarin Tawar\r\n50 gram Terong', 'Pertama masak 20 gram beras merah menggunakan 150 ml kaldu. tambahkan 25 gram hati ayam. masak hingga matang dan menjadi bubur.\r\n\r\nKemudian masukkan 50 gram terong yang dipotong kecil dan 50 gram bayam.\r\n\r\nSelanjutnya masak hingga sayuran matang. tambahkan 1 sendok teh margarin tawar.', '10 bulan'),
(62, 'Bubur Kentang Brokoli', '120 ml Air\r\n25 gram Brokoli\r\n40 gram Daging Ayam Tanpa Lemak\r\n200 gram Kentang\r\n100 gram Tahu\r\n40 gram Wortel', 'Pertama cuci daging ayam dan tahu, potong kecil-kecil\r\n\r\nKemudian kupas kentang dan wortel, potong kecil-kecil\r\n\r\nSelanjutnya petik brokoli sesuai kuntum, potong kecil-kecil\r\n\r\nKemudian masukkan daging ayam, tahu, kentang dan wortel kadalam panci.\r\n\r\nLalu tambahkan air dan masak sampai mendidih.\r\n\r\nTutup dan diamkan selama 30 menit.\r\n\r\nMasukkan brokoli matang dalam keadaan tertutup selama 10 menit atau sampai brokoli lunak.\r\n\r\nHaluskan semua bahan ke dalam blender\r\n\r\nTuang dalam mangkuk dan biarkan dingin. hidangkan.', '10 bulan'),
(63, 'Tim Telur Wortel', '100 ml Air Kaldu Ayam\r\n100 gram Nasi Aron Setengah Matang\r\n1/2 sendok teh Seledri (cincang Halus)\r\n4 buah Telur Puyuh\r\n50 gram Wortel', 'Pertama kupas wortel, cuci bersih, dan parut halus.\r\n\r\nKemudian iris halus seledri.\r\n\r\nSelanjutnya iris tipis telur puyuh\r\n\r\nKemudian campurkan nasi, wortel, dan seledri lalu aduk rata. tambahkan air kaldu ayam dan garam, aduk kembali.\r\n\r\nLalu siapkan mangkuk tahan panas. masukkan setengah bagian nasi, beri irisan telur lalu tumpuk dengan sisa nasi dan ratakan.\r\n\r\nKukus selama kurang lebih 30 menit, angkat lalu dinginkan. jika sudah hangat-hangat kuku siap untuk di berikan kepada si kecil.', ''),
(64, 'Bubur Kentang Ayam Sayuran', '25 gram Bayam\r\n25 gram Daging Ayam Cincang\r\n250 ml Kaldu Ayam\r\n10 gram Keju\r\n100 gram Kentang\r\n25 gram Tempe\r\n25 gram Wortel', 'Pertama kukus kentang dan haluskan.\r\n\r\nKemudian cincang halus dagig ayam.\r\n\r\nSelanjutnya kupas wortel, cuci bersih, dan cincang kasar.\r\n\r\nKemudian cuci bersih bayam, dan iris halus,\r\n\r\nLalu cincang kasar tempe.\r\n\r\nMasak kentang, wortel, daging ayam cincang dan tempe dengan kaldu.\r\n\r\nTambahkan bayam dan keju.\r\n\r\nMasak sambil terus diaduk, sampai bubur mengental. Angkat, sajikan', '10 bulan'),
(65, 'Bubur Ayam Kentang Giling', '10 gram Bayam\r\n10 gram Daging Ayam\r\n125 ml Kaldu\r\n10 gram Kentang\r\n1 butir Kuning Telur\r\n10 gram Tomat\r\n10 gram Wortel', '\r\nPertama cincang halus daging ayam.\r\n\r\nKemudian cincang halus tomat dan buang bijinya,\r\n\r\nSelanjutnya kupas wortel, cuci bersih, dan parut.\r\n\r\nKemudian cuci bersih bayam dan iris tipis.\r\n\r\nLalu rebus kentang, daging ayam, wortel, tomat dengan air kaldu.\r\n\r\nMasukan bayam, kuning telur. aduk rata.\r\nMasak sampai matang. Angkat.\r\n\r\nSaring dengan saringan kawat. Sajikan segera.', '10 bulan'),
(66, 'Bubur Anggur Kacang Merah', '50gram Anggur\r\n5 sendok makan ASI\r\n10gram Kacang Merah', 'Pertama kupas anggur dan buang bijinya.\r\n\r\nKemudian didihkan 200 ml air, rebus kacang merah hingga empuk.\r\n\r\nSelanjutnya setelah agak dingin, blender kacang merah beserta air rebusannya dengan anggur dan cairan hingga lembut.\r\n\r\nKemudian tempatkan ke dalam mangkuk dan segera berikan ke bayi.', '10 bulan'),
(67, 'Bubur Pir dan Apel', '75 cc Air\r\n100 ml Asi\r\n50 gram Buah Apel\r\n50 gram Buah Pir\r\n1 sendok makan Tepung Maizena', 'Pertama kupas buah pir dan apel, potong kecil-kecil. kemudian rendam dengan air garam sebentar, tiriskan.\r\n\r\nKemudian larutkan tepung maizena dengan 25 cc air.\r\n\r\nSelanjutnya rebus pir dan apel dengan 50 cc air selama 5 menit. lalu masukkan larutan tepung maizena.\r\n\r\nKemudian masak hingga mendidih sambil diaduk.\r\n\r\nLalu angkat campurkan asi/ susu formula, kemudian saring dengan saringan kawat. siap disajikan hangat-hangat.', ''),
(68, 'Bubur Susu Nabati', '1/2 sendok teh Bawang Bombay\r\n50 gram Daging Sapi Cincang\r\n1 sendok makan Margarin\r\n200 ml Susu Kedelai\r\n50 gram Tepung Terigu\r\n10 gram Wortel, Rebus', 'Pertama cincang halus bawang bombay.\r\n\r\nKemudian cincang halus daging sapi.\r\n\r\nSelanjutnya kupas wortel, cuci bersih, rebus, kemudian haluskan.\r\n\r\nKemudian panaskn margarin, masukkan bawang bombay dan tepung. aduk sampai tepung tidak terasa mentah.\r\n\r\nLalu masukkan daging dan wortel, aduk rata. tuang susu sedikit demi sedikit sambil diaduk agar tepung tidak menggumpal.\r\n\r\nTerus aduk sampai diperoleh bubur susu yang lembut. Sajikan', '10 bulan'),
(69, 'Bubur Siram Bayam', '10 lembar Daun Bayam Merah\r\n200 ml Kaldu Daging Sapi\r\n50 gram Tempe\r\n100 gram Tepung Beras', 'Pertama campur tepung beras dan setengah bagian kaldu, masak sambil diaduk-aduk hingga meletup-letup. angkat. sisihkan.\r\n\r\nKemudian didihkan sisa kaldu, masukkan tempe dan bayam, masak hingga bayam empuk, angkat. haluskan.\r\n\r\nSelanjutnya masukkan ke dalam blender. proses hingga halus. siramkan bayam dan tempe halus di atas bubur beras. sajikan segera.', ''),
(70, 'Bubur Tepung Beras Sari Jeruk', '50 ml ASI\r\n200 ml Air\r\n50 ml Air Jeruk Manis\r\n20 gram Tepung Beras\r\n2 sendok makan Tepung Maizena', 'Pertama campur tepung beras, tepung maizena & air, aduk rata, jerang di atas api, aduk sampai mendidih, angkat.\r\n\r\nKemudian masukkan asi atau susu formula, aduk rata, tunggu sampai agak dingin.\r\n\r\nSelanjutnya tuangi air jeruk manis, hidangkan segera.', '10 bulan'),
(71, 'Bubur Susu Kedelai', '300 ml Susu Kedelai\r\n50 gram Tahu\r\n50 gram Tempe\r\n2 sendok makan Tepung Maizena', 'Pertama haluskan dengan blender tempe, tahu dan susu kedelai. tuang ke dalam panci.\r\n\r\nKemudian tambahkan larutan tepung maizena. masak dan aduk-aduk hingga mengental. sajikan', '10 bulan'),
(72, 'Nasi Tim Ikan Gurame', '45 gram Beras\r\n40 gram Daging Ikan Gurame\r\n25 gram Daun Bayam\r\n45 gram Kacang Hijau\r\n500 ml Kaldu Ikan Gurame\r\n2 butir Kuning Telur\r\n120 ml Santan\r\n25 gram Tomat\r\n25 gram Wortel', 'Pertama cuci beras sampai bersih\r\n\r\nKemudian haluskan ikan gurame, sisihkan\r\n\r\nSelanjutnya haluskan kacang hijau.\r\n\r\nKemudian cuci bersih daun bayam dan iris halus.\r\n\r\nLalu rebus beras dengan kaldu ikan gurame diatas bara api sedang, aduk rata sampai menjadi bubur.\r\n\r\nMasukkan dan campurkan bahan lainnya kedalam bubur, aduk rata lalu angkat.\r\n\r\nMasukkan bubur kedalam mangkok atau bungkus dengan daun pisang menjadi 3 porsi\r\n\r\nKukus bubur sampai matang, kemudian angkat.\r\nSajikan bubur dalam selagi hangat.', '10 bulan'),
(73, 'Nasi Tim Ikan Tenggiri Jagung Manis', '15 gram Daging Ikan Tenggiri\r\n30 gram Jagung Manis\r\n150 cc Kaldu\r\n25 gram Kangkung\r\n1 sendok makan Mentega\r\n50 gram Nasi Aron\r\n1 tangkai Seledri\r\n25 gram Tomat', 'Pertama rebus jagung manis dan parut halus.\r\n\r\nKemudian kupas tomat, cincang halus dan buang bijinya.\r\n\r\nSelanjutnya iris halus seledri dan kangkung.\r\n\r\nKemudian ambil mangkuk tahan panas.\r\n\r\nLalu masukkan nasi aron, ikan tenggiri, jagung manis, kangkung, dan tomat.\r\n\r\nBeri air kaldu sampai bahan terendam, lalu tim.\r\n\r\nSesaat sebelum matang, masukkan mentega dan seledri, tim kembali hingga matang.\r\n\r\nSetelah matang, angkat dan siap dihidangkan.', '10 bulan'),
(74, 'Bubur Susu Kuning Telur Jagung Manis', '100 ml Air Matang\r\n100 gram Jagung Manis\r\n25 gram Keju Parut\r\n1 butir Kuning Telur\r\n3 sendok makan Susu Bubuk', 'Pertama pipil jagung manis.\r\n\r\nKemudian campurkan semua bahan kecuali keju parut lalu proses dengan blender sampai halus.\r\n\r\nSelanjutnya saring menggunakan penyaring halus lalu buang ampasnya.\r\n\r\nKemudian masak hingga mendidih dan matang.\r\n\r\nLalu angkat, sajikan selagi hangat dengan taburan keju parut.', '10 bulan'),
(75, 'Jus Pinky Strawberry Pisang', '200 ml Air Matang\r\n2 sendok makan Madu Murni\r\n1 buah Pisang Ambon\r\n100 gram Stroberi', 'Pertama cuci bersih stroberi lalu potong-potong kecil\r\n\r\nKemudian kupas pisang dan potong-potong kecil\r\n\r\nSelanjutnya masukkan kedua bahan ke dalam blender, tambahkan air dan blender hingga halus\r\n\r\nKemudian tuang ke dalam gelas saji, tambahkan madu, aduk hingga tercampur rata\r\n\r\nLalu jus yang cantik dan lezat siap dinikmati', '12 bulan'),
(76, 'Jus Naga Ungu', '100 ml Air Perasan Jeruk Manis\r\n1 buah Naga Merah\r\n200 gram Semangka', 'Pertama ambil bagian dalam buah naga, lalu potong-potong kecil\r\n\r\nKemudian potong-potong semangka\r\n\r\nSelanjutnya campurkan ketiga bahan di atas ke dalam blender, lalu haluskan\r\n\r\nKemudian tuang ke dalam gelas saji, dan siap dihidangkan', '12 bulan'),
(77, 'Perkedel Panggang Ikan Tenggiri', '1 putih telur, kocok lepas\r\n1 sendok makan Air Jeruk Nipis\r\n3 siung Bawang Merah\r\n3 siung Bawang Putih\r\n200 gram Daging Ikan Tenggiri\r\n1 lembar Daun Bawang, Iris Halus\r\nsecukupnya Garam\r\n200 gram Kentang Kupas, Kukus Matang, Dinginkan Lalu Haluskan\r\n1 sendok teh Ketumbar Sangrai\r\nsecukupnya Minyak S', 'Pertama lumuri ikan dengan air jeruk nipis dan garam, ratakan, diamkan selama 15 menit. kemudian cuci bersih ikan dan tiriskan\r\n\r\nKemudian haluskan ikan dengan food processor atau blender, lalu campur dengan kentang yang sudah dihaluskan, putih telur, dan bumbu halus,\r\n\r\nSelanjutnya aduk-aduk hingga tercampur rata. tambahkan daun bawang dan aduk lagi hingga semua bahan tercampur rata\r\n\r\nKemudian bagi adonan menjadi beberapa bagian, masing-masing kepal dan bentuk bulat pipih\r\n\r\nLalu panaskan pan pemanggang, olesi minyak sayur tipis-tipis, panggang perkedel ikan hingga matang (kedua sisinya berwarna agak kecoklatan dan matang)\r\n\r\ntata dalam piring saji dan siap dinikmati', '12 bulan'),
(78, 'Kaserol Daging Wortel', '1 batang daun seledri\r\n25 gram Bawang Bombay\r\n50 gram Daging Giling\r\n20 ml Jus Apel\r\n40 ml Kaldu Sapi\r\n15 gram Keju Chedar\r\n1/2 sendok teh Mentega Tawar\r\n1 sendok teh Tepung Terigu\r\n30 gram Tomat\r\n50 buah Wortel', 'Pertama kupas wortel, cuci bersih, dan potong kecil-kecil.\r\n\r\nKemudian kupas bawang bombay dan iris halus.\r\n\r\nSelanjutnya haluskan tomat.\r\n\r\nKemudian parut keju.\r\n\r\nLalu panaskan mentega, tumis bawang bombay hingga harum.\r\n\r\nTambahkan daging giling, wortel dan tomat hingga layu dan matang.\r\n\r\nTambahkan jus apel, kaldu dan daun seledri. Taburi tepung terigu. Masak hingga air berkurang.\r\n\r\nSajikan dalam mangkuk, taburi keju.', '12 bulan'),
(79, 'Kembang Kol Kentang Panggang', '1 siung Bawang Putih\r\n50 gram Daging Ayam\r\n25 gram Keju Parut\r\n100 gram Kembang Kol\r\n100 gram Kentang\r\n1/2 sendok teh Mentega Tawar', 'Pertama kukus 100 gram kentang dan 100 gram kembang kol. haluskan keduanya.\r\n\r\nKemudian tumis 1 siung bawang putih, menggunakan 1/2 sendok teh mentega tawar.\r\n\r\nSelanjutnya masukkan ayam, masak hingga matang.\r\n\r\nKemudian campurkan dengan kentang, taburi 25 gram keju parut. panggang hingga matang.', '12 bulan'),
(80, 'Bubur Seafood Beras Merah', '400 ml Air\r\n1 sendok teh Air Jeruk Lemon\r\n1 butir Bawang Merah\r\n1 siung Bawang Putih\r\n50 gram Beras Merah\r\n25 gram Daging Ikan Tenggiri\r\n4 lembar Daun Seledri\r\n1 sendok makan Margarin\r\n1 sendok makan Udang\r\n20 gram Wortel', 'Pertama kupas udang kemudian cincang halus.\r\n\r\nKemudian cincang halus bawang putih dan bawang merah.\r\n\r\nSelanjutnya kupas wortel, cuci bersih dan parut kasar.\r\n\r\nKemudian iris halus daun seledri.', '12 bulan'),
(81, 'Tim Tahu Brokoli', '300 ml Air Kaldu\r\n1 sendok makan Bawang Bombay\r\n1 siung Bawang Putih\r\n80 gram Brokoli\r\n50 gram Daging Ayam\r\n1 sendok teh Garam\r\n1/3 sendok teh Gula Pasir\r\n1 sendok makan Margarin\r\n1 buah Tahu Cina\r\n2 sendok makan Tepung Beras\r\n1 buah Tomat', 'Pertama parut halus bawang putih.\r\n\r\nKemudian cincang halus bawang bombay.\r\n\r\nSelanjutnya cincang halus daging ayam.\r\n\r\nKemudian cincang tomat dan buang bijinya.\r\n\r\nLalu haluskan tahu.\r\n\r\nRebus brokoli kemudian cincang.\r\n\r\nPanaskan margarin, lalu tumis bawang putih dan bawang bombay sampai harum dan matang. Masukkan daging ayam cincang, tomat, garam, dan gula pasir. Masak sampai daging ayam matang. Tambahkan tahu cina dan brokoli rebus. Aduk-aduk, kemudian angkat.\r\n\r\nBagi tumisan menjadi tiga bagian dan tempatkan dalam mangkuk tahan panas. Sisihkan.\r\n\r\nLarutkan tepung beras dengan kaldu. Bagi menjadi tiga bagian, lalu tuang ke masing-masing mangkuk. Kukus selama 30 menit atau sampai matang. Angkat, sajikan.', '12 bulan'),
(82, 'Onigiri Tuna', '200 ml Air\r\n30 gram Bayam\r\n30 gram Beras Putih\r\n30 gram Tuna', 'Pertama masak 30 gram beras putih dengan 200 ml air hingga lunak. Angkat. Sisihkan.\r\n\r\nKemudian cincang lalu rebus 30 gram tuna dan 30 gram bayam hingga matang. Angkat.\r\n\r\nSelanjutnya pipihkan nasi, letakkan tuna dan bayam di atasnya. \r\nKepal seperti onigiri.', '12 bulan'),
(83, 'Puding Roti Pisang', '50 gram Keju Parut\r\n2 buah Pisang Ambon\r\n3 lembar Roti Tawar Gandum\r\n150 cc Susu Cair', 'Pertama hancurkan pisang hingga lembut, tambahkan roti tawar yang sudah disobek-sobek.\r\n\r\nKemudian tambahkan susu dan keju.\r\n\r\nSelanjutnya tuang ke dalam mangkuk tahan panas. kukus selama 10-15 menit.', '12 bulan'),
(84, 'Bubur Beras Saus Jeruk', '100 ml Air Jeruk Manis\r\n200 ml Air Matang Hangat\r\n1/2 buah Apel\r\n50 gram Tepung Beras', 'Pertama kupas apel, cuci bersih, dan potong dadu.\r\n\r\nKemudian membuat saus buah rebus apel hingga lunak. angkat dan haluskan bersama air jeruk manis. sisihkan.\r\n\r\nSelanjutnya campur tepung beras dengan air hangat, aduk rata.\r\n\r\nKemudian tuang bubur ke dalam mangkuk kecil, beri saus jeruk. sajikan.', '12 bulan'),
(85, 'Brokoli Tahu Panggang', '50 gram Brokoli\r\n75 gram Daging Sapi Cincang\r\n50 gram Keju Cheddar\r\n1/2 sendok makan Mentega\r\n75 gram Tahu\r\n75 gram Tomat Merah', 'Pertama brokoli, cincang halus, tahu potong dadu kecil, keju cheddar, parut halus.\r\n\r\nKemudian panaskan mentega dalam wajan untuk menumis daging cincang, lalu aduk hingga berubah warna. tuang air, aduk hingga mendidih dan air habis. angkat dan sisihkan.\r\n\r\nSelanjutnya semir pinggan tahan panas dengan mentega. susun brokoli dan tahu dalam pinggan.\r\n\r\nKemudian tambahkan daging tumis, aduk rata, lalu taburi keju parut.\r\n\r\nLalu panggang dalam oven panas 180º c selama 20 menit hingga matang.\r\n\r\nAngkat, biarkan agak dingin lalu sajikan.', '12 bulan'),
(86, 'Bubur Kacang Hijau Saus Tomat', '100 cc ASI\r\n200 cc Air Hangat\r\n30 gram Tepung Kacang Hijau\r\n1 buah tomat', 'Pertama tepung kacang hijau yang kita pakai adalah tepung kacang hijau siap pakai untuk bayi.\r\n\r\nKemudian asi dapat diganti dengan 2 sendok takar peres susu bubuk formula, larutkan dalam 100 cc air matang\r\n\r\nSelanjutnya terlebih dahulu kita buat saus tomat. seduh tomat dengan air panas lalu kupas. haluskan dan saring ke dalam panci kecil.\r\n\r\nKemudian tambahkan air lalu rebus hingga mendidih. kentalkan dengan maizena, tambahkan air jeruk. aduk rata.\r\n\r\nLalu kemudian kita buat buburnya dengan mencampur tepung kacang hijau dengan air hangat. aduk rata lalu panaskan sambil terus diaduk hingga mendidih. angkat. tuang ke dalam mangkuk kecil.\r\n\r\nTambahkan susu dan saus tomat, aduk rata.', '12 bulan'),
(87, 'Pure Jambu Beras Merah', '100 ml ASI\r\n75 ml Air\r\n100 gram Daging Jambu Biji\r\n100 gram Tepung Beras Merah', 'Pertama masak tepung beras merah dengan air hingga matang.\r\n\r\nKemudian blender daging jambu biji menggunakan blender.\r\n\r\nSelanjutnya campur dengan bubur beras merah.\r\n\r\nKemudian tambahkan asi perah atau susu formula.', '12 bulan'),
(88, 'Bubur Jagung Susu', '\r\n100 ml Air\r\n1 sendok teh Gula Merah\r\n100 gr Jagung Muda Pipilan\r\n3 sendok takar Susu Formula', 'Pertama masukkan jagung muda, gula merah dan air ke dalam blender, haluskan. keluarkan dari blender saring dan buang ampasnya\r\n\r\nKemudian panaskan diatas api kecil, aduk hingga kental, angkat dari api\r\n\r\nSelanjutnya masukkan susu formula aduk kembali sampai tercampur rata. Hidangkan selagi hangat', '12 bulan'),
(89, 'Nasi Ayam', '\r\n350 cc Air\r\n50 gram Daging Ayam\r\n50 gram Nasi Aron\r\n20 gram Tahu\r\n20 gram Wortel', 'Pertama nasi aron adalah nasi setengah matang.\r\n\r\nKemudian haluskan tahu hingga lembut.\r\n\r\nSelanjutnya kupas wortel, cuci bersih, dan parut halus.\r\n\r\nKemudian cincang halus daging ayam.\r\n\r\nLalu masukkan nasi aron, daging ayam, tahu, dan wortel ke dalam mangkuk tahan panas. tambahkan sedikit air. aduk rata.\r\n\r\nRendam mangkuk tersebut di mangkuk ukuran sedang berisi air. Tim hingga matang. Angkat.\r\n\r\nSetelah agak dingin, haluskan. Sajikan.', '12 bulan'),
(90, 'Bubur Makaroni Ayam', '250 cc Air\r\n35 gram Brokoli\r\n35 gram Daging Ayam Cincang\r\n50 gram Keju Parut\r\n50 gram Macaroni', 'Pertama rebus macaroni hingga empuk selama lebih kuang 10 menit, angkat.\r\n\r\nKemudian rebus ayam cincang sampai matang dengan 250 cc air.\r\n\r\nSelanjutnya masukkan macaroni, rebus sampai agak lunak.\r\n\r\nKemudian masukkan brokoli, rebus sambil diaduk hingga semua bahan matang.\r\n\r\nLalu angkat, dan masukkan keju parut. setelah agak dingin, blender kasar. tuang ke dalam mangkuk kecil, dan sajikan.', '12 bulan');
INSERT INTO `mpasi` (`id`, `nama`, `bahan`, `resep`, `usia`) VALUES
(91, 'Tim Kentang Teri', '150 ml Air\r\n30 gram Buncis\r\n50 gram Kentang\r\n30 gram Teri Basah\r\n25 gram Tomat', 'Pertama kupas kentang kemudian parut kasar.\r\n\r\nKemudian tumbuh halus teri basah, atau bisa juga diblender.\r\n\r\nSelanjutnya bersihkan serat buncis (disiangi) kemudian cincang.\r\n\r\nKemudian kupas tomat dan cincang.\r\n\r\nLalu masukkan kentang, teri, tomat dan buncis kedalam mangkuk yang tahan panas kemudian aduk merata.\r\n\r\nTambahkan air, lalu kukus atau tim hingga matang. angkat.\r\n\r\nTuang ke dalam mangkuk kecil, sajikan setelah dingin.\r\n\r\nBila masih terlalu kasar, dapat dihaluskan dengan blender atau food processor.', '12 bulan'),
(92, 'Tim Jagung Daging', '1 siung Bawang Putih\r\n50 gram Daging Giling\r\n50 gram Jagung Serut\r\n1 sendok teh Mentega Tawar\r\n75 gram Nasi Tim\r\n25 gram Sawi Hijau\r\n25 gram Wortel Parut', '\r\nPertama tumis 1 siung bawang putih yang sudah dihaluskan menggunakan 1 sendok teh mentega tawar.\r\n\r\nKemudian masukkan 50 gram daging giling, 50 gram jagung serut, dan 25 gram wortel diparut kasar. Masak hingga lunak dan matang.\r\n\r\nSelanjutnya tambahkan 25 gram sawi hijau yang diiris halus. \r\nCetak 75 gram nasi tim, tambahkan tumisan daging di atasnya.', '12 bulan'),
(93, 'Sup Tuna Wortel', '600 ml Air\r\n30 gram Brokoli, Cincang\r\n30 gram Daging Ikan Tuna\r\n1 sendok makan Minyak Zaitun\r\n50 gram Wortel', 'Pertama cincang halus daging tuna.\r\n\r\nKemudian kupas wortel, cuci bersih,dan potong dadu.\r\n\r\nSelanjutnya rebus ikan, wortel dan brokoli hingga matang.\r\n\r\nKemudian tambahkan minyak zaitun. angkat. setelah dingin, haluskan.\r\n\r\nLalu pindahkan ke dalam mangkuk, sajikan.', '12 bulan'),
(94, 'Ubi Bayam Susu', '100 ml Asi\r\n25 gram Bayam\r\n50 gram Ubi', 'Pertama kupas ubi, cuci bersih, kemudian potong dadu.\r\n\r\nKemudian rebus ubi hingga hampir matang.\r\n\r\nSelanjutnya masukkan bayam, masak hingga bahan matang. angkat.\r\n\r\nKemudian haluskan ubi dan bayam, tambahkan asi atau susu formula yang dicairkan, aduk rata. sajikan dingin.', '12 bulan'),
(95, 'Tim Hati Sapi Wortel', '1/4 siung Bawang Putih\r\n25 gram Daun Bayam\r\n50 gram Hati Sapi\r\n100 ml Kaldu Kaki Ayam\r\n50 gram Labu Siam\r\n1/2 sendok teh Minyak Wijen\r\n100 gram Nasi Aron\r\n25 gram Wortel Parut', 'Pertama potong dadu kecil hati sapi.\r\n\r\nKemudian kupas wortel, cuci bersih, dan parut halus.\r\n\r\nSelanjutnya cuci bayam dan iris halus.\r\n\r\nKemudian kupas labu siam, cuci bersih, dan parut halus.\r\n\r\nLalu cincang halus bawang putih.\r\n\r\nCampur semua bahan lalu aduk sampai rata\r\n\r\nMasukkan dalam mangkuk tahan panas\r\n\r\nkukus selama 25 menit\r\n\r\nAngkat lalu sajikan selagi hangat', '12 bulan'),
(96, 'Bubur Daging Tempe', '15 gram Bawang Bombay\r\n50 gram Beras\r\n100 gram Daging Sapi Cincang\r\n1 lembar Daun Salam\r\n1 sendok teh Garam\r\n2 sendok teh Garam\r\n1 sendok teh Kaldu Ayam Bubuk\r\n375 ml Kaldu Ikan\r\n1 sendok makan Kecap Jepang\r\n1/2 sendok makan Kecap Manis\r\n1/2 sendok teh Merica Bubuk\r\n1 sendok makan Minyak Sayur\r\n35 g', 'Pertama cuci bersih beras.\r\n\r\nKemudian potong dadu tempe.\r\n\r\nSelanjutnya cincang bawang bombay.\r\n\r\nKemudian campur beras, kaldu ikan, kaldu ayam bubuk, garam, dan daun salam menjadi satu lalu masak di atas api kecil hingga menyatu dan kental, angkat\r\n\r\nLalu tumis bawang putih hingga wangi\r\n\r\nMasukkan daging lalu aduk hingga berubah warna\r\n\r\nTambahkan tempe lalu aduk rata\r\n\r\nMasukkan bumbu, masak hingga meresap, angkat\r\n\r\nSajikan bubur dengan tumisan daging', '12 bulan'),
(97, 'Karamel Ubi Merah', '1 helai daun pandan\r\n50 ml Air\r\n1/8 sendok teh Garam\r\n100 gram Gula Merah\r\n2 sendok makan Gula Pasir\r\n500 ml Minyak Goreng\r\n5 buah Ubi Merah\r\n1 sendok makan Wijen Putih Sangrai', 'Pertama serut halus gula merah.\r\n\r\nKemudian sangrai wijen\r\n\r\nSelanjutnya sikat kulit ubi dan cuci hingga benar-benar bersih.\r\n\r\nKemudian potong bentuk dadu ukuran 3 x 3 cm\r\n\r\nLalu panaskan minyak, goreng ubi hingga berwarna kecoklatan dan matang. angkat dan tiriskan\r\n\r\nMembuat aus: campur gula merah, garam, daun pandan, gula pasir dan air. rebus hingga gula larut dan kental\r\n\r\nMasukkan ubi goreng, aduk hingga tercampur rata. angkat\r\n\r\nTaburi ubi dengan wijen sangrai, sajikan', '24 bulan'),
(98, 'Dadar Nasi', '1/4 sendok teh merica\r\n1/2 sendok teh Garam\r\n1/2 sendok makan Kacang Polong Beku\r\n1 sendok makan Keju Parut\r\n1/2 sendok makan Margarin\r\n50 gram Nasi Putih\r\n1 butir Telur', 'Pertama campur semua bahan, kecuali margarin\r\n\r\nKemudian panaskan cetakan kue lupur, olesi dengan margarin. tuang satu sendok adonan ke dalam cetakan, masak sampai nasi matang, angkat.\r\n\r\nSelanjutnya hidang dengan sayur atau lauk pauk.', '24 bulan'),
(99, 'Bola Udang Roti', '\r\n1/2 sendok teh Garam\r\n300 ml Minyak Goreng\r\n2 lembar Roti Tawar\r\n1 butir Telur\r\n100 gram Udang', 'Pertama kupas udang dan cincang halus.\r\n\r\nKemudian haluskan bersama-sama roti tawar dan udang kupas menggunakan blender/chopper\r\n\r\nSelanjutnya angkat, beri telur dan garam\r\n\r\nKemudian bentuk bulat memakai 2 sendok teh lalu gulingkan pada potongan roti tawar bentuk dadu secara merata.\r\n\r\nLalu goreng dengan minyak panas sampai warnanya kuning kecoklatan. angkat dan hidangkan.', '24 bulan'),
(100, 'Bola-bola Sayur', '150 gram Ayam\r\n1/2 buah Bawang Bombay\r\n2 siung Bawang Putih\r\n5 batang Buncis\r\n1 sendok teh Garam\r\n1/2 sendok teh Gula\r\n1 buah Jagung Manis\r\n1 sendok makan Margarin\r\n100 ml Susu Cair\r\n2 butir Telur\r\n100 gram Tepung Roti\r\n2 sendok makan Tepung Terigu\r\n1 buah Wortel', 'Pertama cincang halus bawang bombay dan bawang putih.\r\n\r\nKemudian cincang halus daging ayam.\r\n\r\nSelanjutnya buang serat buncis, cuci bersih, dan iris halus.\r\n\r\nKemudian sisir jagung manis dan rebus hingga matang.\r\n\r\nLalu kupas wortel, cuci bersih, dan potong dadu. kemudian rebus sebentar.\r\n\r\nPanaskan margarin, tumis bawang bombay dan bawang putih sampai harum.\r\n\r\nMasukkan ayam giling, masak hingga berubah warna. masukkan secara bertahap buncis, jagung manis, wortel, garam, dan gula pasir, aduk rata.\r\n\r\nMasukkan tepung terigu, aduk rata lalu tuang susu cair masak hingga mengental. angkat dan dinginkan.\r\n\r\nAmbil satu sendok teh adonan lalu bulatkan. celupkan ke dalam kocokan telur lalu gulingkan di atas tepung roti hingga rata.\r\n\r\nGoreng dalam minyak panas sedang hingga matang.', '24 bulan'),
(101, 'Tim Brokoli Tempe', '50 gram Beras\r\n25 gram Brokoli\r\n1/2 sendok teh Garam\r\n400 cc Kaldu Ayam\r\n2 sendok teh Minyak\r\n50 gram Tempe\r\n15 gram Teri Nasi Tawar', 'Pertama cincang halus brokoli.\r\n\r\nKemudian rebus tempe kemudian haluskan.\r\n\r\nSelanjutnya sangrai teri nasi kemudian haluskan.\r\n\r\nKemudian masak beras dalam 200 cc kaldu hingga setengah matang, angkat.\r\n\r\nLalu tambahkan bahan lain dan sisa kaldu, kecuali brokoli, aduk hingga rata.\r\n\r\nTaruh di mangkuk tahan panas dan tim (rebus dalam panci yang lebih besar yang berisi air).\r\n\r\nSejenak sebelum diangkat, tambahkan brokoli. teruskan tim hingga matang.\r\n\r\nSajikan hangat-hangat.', '24 bulan'),
(102, 'Sup Oyong Soun', '5 buah Bakso\r\n1 batang Bawang Daun\r\n1 siung Bawang Putih\r\n1 sendok teh Garam\r\n500 cc Kaldu\r\n1 sendok makan Minyak Sayur\r\n1 buah Oyong\r\n1 batang Seledri\r\n50 gram Soun\r\n1 buah Tahu', 'Pertama kupas oyong, potong-potong, dan cuci bersih.\r\n\r\nKemudian potong dadu tahu.\r\n\r\nSelanjutnya potong bakso menjadi 8 bagian.\r\n\r\nKemudian rendam soun dengan air panas. angkat dan tiriskan. gunting sesuai selera.\r\n\r\nLalu iris serong daun bawang.\r\n\r\nIris halus seledri.\r\n\r\nTumis bawang putih sampai harum.\r\n\r\nMasukkan tumisan bawang putih ke dalam kaldu, didihkan.\r\n\r\nTambahkan oyong, tahu, dan bakso, masak sampai sayuran lunak.\r\n\r\nMasukkan bawang daun, seledri, dan garam, aduk rata.\r\n\r\nMasak sampai mendidih, angkat.\r\n\r\nLetakkan soun di mangkuk saji siram dengan sup oyong. ', '24 bulan'),
(103, 'Pai Sayuran', '1 buah Jagung Manis\r\n100 gram Kacang Polong\r\n50 gram Keju Cheddar\r\n125 gram Margarin\r\n1/2 sendok teh Merica Bubuk\r\n200 ml Susu Cair\r\n2 butir Telur\r\n350 gram Tepung Terigu\r\n100 gram Wortel', 'Pertama kocok telur hingga berbuah.\r\n\r\nKemudian kupas wortel, cuci bersih dan rebus. kemudian potong dadu.\r\n\r\nSelanjutnya rebus jagung manis kemudian pipil.\r\n\r\nKemudian campur semua bahan kulit, aduk sampai rata. gilas setebal 3/4 cm, kemudian masukkan ke dalam loyang pai atau pinggan tahan panas berukuran 20 cm yang sudah diolesin margarin tipis-tipis. sisihkan.\r\n\r\nLalu campur bahan isi sampai rata. tuang ke atas kulit pai. panggang dalam oven bersuhu 180 derajat celcius sampai matang dan isi pai menjadi padat. angkat.\r\n\r\nSajikan bersama saus tomat.', '24 bulan'),
(104, 'Kentang Panggang Isi Kornet', '1 batang Daun Bawang\r\n1 sendok teh Garam Halus\r\n500 gram Kentang\r\n100 gram Kornet Kalengan\r\n1 sendok makan Margarin', 'Pertama cuci kentang, panggang dalam oven/microwave sampai matang, potong 1/4 bagian atasnya kupas kulitnya, sisihkan. kerok bagian atas yang dipotong tadi sehingga kentang berbentuk mangkuk.\r\n\r\nKemudian campur hasil dari proses pengerokan dengan 1/4 bagian hasil potongan, haluskan.\r\n\r\nSelanjutnya panaskan margarin, tumis daun bawang, masukkan garam, merica dan kornet, masak sampai matang/kering.\r\n\r\nKemudian campur adonan kentang yang dihaluskan dengan adonan kornet. masukkan kembali kedalam mangkuk kentang sehingga bentuk kentang seperti semula.\r\n\r\nLalu panggang kembali kentang sampai bagian atasnya kering. hidangkan.', '24 bulan'),
(105, 'Sup Jagung Hati Ayam', '\r\n1 siung Bawang Putih\r\n1 sendok teh Garam\r\n1 buah Hati Ayam Rebus\r\n50 gram Jagung Manis\r\n200 ml Kaldu Ayam\r\n1 sendok teh Mentega\r\n50 ml Susu\r\n1 sendok teh Tepung Terigu\r\n20 gram Wortel', 'Pertama cincang halus bawang putih.\r\n\r\nKemudian serut halus jagung manis.\r\n\r\nSelanjutnya kupas wortel, cuci bersih, dan iris halus.\r\n\r\nKemudian rebus hati ayam, dan potong dadu.\r\n\r\nLalu tumis bawang putih hingga wangi.\r\n\r\nMasukkan tepung terigu, aduk hingga rata.\r\n\r\nTuangi kaldu, aduk hingga licin.\r\n\r\nTambahkan jagung, wortel dan bahan lainnya.\r\n\r\nDidihkan hingga sayuran lunak.\r\n\r\nAngkat, sajikan hangat.', '24 bulan'),
(106, 'Sup Kentang Brokoli', '1 sendok teh Bawang Bombay\r\n50 gram Brokoli\r\n50 gram Dada Ayam\r\n200 ml Kaldu Ayam\r\n50 gram Kentang\r\n1 sendok teh Minyak Zaitun\r\n50 gram Tahu Sutra', 'Pertama kupas kentang dan cuci bersih brokoli lalu potong - potong.\r\n\r\nKemudian tumis bawang bombay dengan minyak zaitun hingga harum lalu tuangi kaldu ayam.\r\n\r\nSelanjutnya masukkan potongan kentang hingga setengah matang.\r\n\r\nKemudian masukkan brokoli dan tahu, masak terus hingga semua bahan matang.\r\n\r\nLalu angkat dan biarkan agak dingin lalu proses dengan blender hingga halus.\r\n\r\nTuang kedalam mangkuk saji dan taburi dengan ayam.', '24 bulan'),
(107, 'Sop Krim Ayam', '1 cangkir Asi\r\n1 buah Dada Ayam Tanpa Tulang Dan Kulit\r\n1/2 sendok teh Tepung Maizena', 'Pertama bersihkan daging ayam dari lemak, cuci bersih lalu potong dadu.\r\n\r\nKemudian rebus ayam dengan air sampai matang.\r\n\r\nSelanjutnya angkat dan tiriskan. simpan air kaldunya.\r\n\r\nKemudian campur ayam, tepung maizena dan sedikit kaldu, blender hingga halus.\r\n\r\nLalu gunakan sisa kaldu untuk mengencerkan adonan hingga kekentalan yang di inginkan.\r\n\r\nSaat akan di sajikan tambahkan asi / susu formula.', '24 bulan'),
(108, 'Sate Buah Pelangi', '2 buah Air Jeruk Manis Untuk Saus\r\n100 gram Belimbing\r\n3 sendok makan Madu Untuk Saus\r\n100 gram Melon\r\n100 gram Nanas\r\n100 gram Semangka\r\n12 buah Tusukan Sate', 'Pertama kupas buah-buahan cuci bersih, dan potong dadu.\r\n\r\nKemudian tusuk potongan buah-buahan secara selang-seling dengan tusuk sate.\r\n\r\nSelanjutnya campurkan semua bahan untuk sausnya.\r\n\r\nKemudian sebelum dihidangkan, siram sate buah dengan sausnya.', '24 bulan'),
(109, 'Tim Labu Kuning', '400 ml Air Kaldu Ikan\r\n50 gram Daging Ikan Salmon\r\n1 butir Kuning Telur\r\n300 gram Labu Kuning\r\n1 sendok makan Reju Ricotta\r\n50 gram Tempe', '\r\nPertama kupas labu kuning, cuci bersih, dan potong dadu.\r\n\r\nKemudian kukus labu kuning kemudian haluskan.\r\n\r\nSelanjutnya rebus ikan salmon, kemudian haluskan dagingnya.\r\n\r\nKemudian kukus tempe kemudian haluskan.\r\n\r\nLalu campur semua bahan, aduk rata.\r\n\r\nTuang adonan dalam 2 buah mangkuk tahan panas, tutup dengan lembaran aluminium foil.\r\n\r\nPanggang dalam oven hingga matang, dalam pinggan berisi sedikit air. angkat.\r\n\r\n', '24 bulan'),
(110, 'Tim Makaroni Kacang Polong', '25 gram Daging Ayam\r\n25 gram Kacang Polong\r\n300 cc Kaldu\r\n10 gram Keju Parut\r\n25 gram Makaroni\r\n25 gram Tahu Potong\r\n25 gram Tomat', 'Pertama cincang halus daging ayam.\r\n\r\nKemudian potong dadu tahu.\r\n\r\nSelanjutnya iris halus tomat dan buang bijinya.\r\n\r\nKemudian rebus makaroni dengan daging ayam, tahu, dan kaldu.\r\n\r\nLalu masukkan kacang polong dan tomat,\r\n\r\nMasak sambil di aduk hingga matang. angkat.\r\n\r\nTempatkan dalam piring saji,\r\n\r\nBeri taburan keju parut.\r\n', '24 bulan'),
(111, 'Mashed Potatoes', '1/2 sendok teh Garam\r\n750 gram Kentang\r\n3 sendok teh Margarin\r\n1 sendok teh Merica Bubuk\r\n1/2 sendok teh Pala Bubuk\r\n225 ml Susu Cair', 'Pertama kukus kentang hingga matang dan lunak\r\n\r\nKemudian kupas dan haluskan selagi panas, bisa ditumbuk atau di blender\r\n\r\nSelanjutnya campur kentang dan bahan lainnya, masak di atas api kecil sambil diaduk hingga matang dan kental, angkat\r\n\r\nKemudian sajikan hangat-hangat', '24 bulan'),
(112, 'Nasi Tim Ayam Wortel Keju', '2 sendok makan Beras\r\n25 gram Daging Ayam\r\n300 ml Kaldu Ayam\r\n10 gram Keju Parut\r\n200 ml Santan\r\n25 gram Tahu\r\n25 gram Tomat\r\n5 gram Wortel', 'Pertama cincang halus daging ayam.\r\n\r\nKemudian potong dadu tahu.\r\n\r\nSelanjutnya kupas wortel, cuci bersih, dan parut kasar.\r\n\r\nKemudian rendam tomat dalam air panas, kupas kulitnya dan haluskan, dan ambil airnya\r\n\r\nLalu campur beras dengan santan, rebus hingga lunak.\r\n\r\nNasi santan di campur dengan kaldu, daging ayam, air tomat, tahu, dan wortel. aduk rata.\r\n\r\nTuang dalam wadah tahan panas, kukus hingga matang.\r\n\r\nAngkat dan sajikan hangat.', '24 bulan');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `mpasi`
--
ALTER TABLE `mpasi`
  ADD PRIMARY KEY (`id`);
ALTER TABLE `mpasi` ADD FULLTEXT KEY `index_name` (`nama`,`bahan`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `mpasi`
--
ALTER TABLE `mpasi`
  MODIFY `id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=113;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
